### PR TITLE
Initial backend work

### PR DESCRIPTION
**Pull request by CuriousG102**
More work on backend code. Non-functional but when I'm done with my current branch (page_and_javascript_integration) we should be close to a small demo, albeit with no way for users to export data yet.

### CODE REVIEW

**Comment by CuriousG102** [comment]
@budang

**Comment by budang** [comment]
A few things:
- **overlord.post** is never set to be true; thus, the following will never be run and a user will be able to click submit and post multiple times

``` javascript
if (this.posting) { 
     window.alert('Submission in progress, please wait.');
     return;
 }
```
- I think we should check if a user has answered the required questions before being allowed to submit; for example:

``` javascript
$('#submit').click(function() {
     if(question_1_answer != undefined && question_2_answer != undefined)   
          overlord.submit();
     else
          alert('Please answer all required questions.');
});
```
- Why do we need a 10 second timeout before making our post request? Is this just a temp value?

Let me know; good work

**Comment by CuriousG102** [comment]
@budang 
Good spot on posting. I'll fix that.

That's not what timeout does: It decides that any AJAX requests have failed after receiving no  response within 10 seconds.

In terms of verification, you are correct that we should have a way to bounce, but we don't want to hardcode a number of steps or anything. How about we introduce a way for a step to bounce the submit process. So, for example, we can have a global 
`var NOT_READY_TO_SUBMIT="Not submittable";`

When a step function is called if it has a problem it will just `throw NOT_READY_TO_SUBMIT;`. Before doing that, it could also put an error message in the appropriate div containing a step's html (e.g. a red box with text "You must fill out this question").

Inside of the loop on steps, I can just write this:

```
var unsuccessful = false;
$.each(this.steps, function(i, el) {
            var name = el[0], callback = el[1];
            try {
            submission['steps'][name] = callback(); }
            catch (err) {
unsuccessful = true;
 if (err !== NOT_READY_TO_SUBMIT) error_func();
}

        });
if (unsuccessful === true) return;
```

Sorry for terrible indentation, typing code in here is hard

**Comment by budang** [comment]
Ah, I must have looked up something else on mistake, that makes sense.

Global variable makes sense to me! After all, not wanting to hardcode steps is kind of the entire idea behind doing the project this way right? lol

**Comment by CuriousG102** [comment]
@budang https://github.com/CuriousG102/turkey/commit/4c8fde5129943d540537185f36bf86d5f9ef76a1

**Comment by budang** [comment]
:+1:

**Pull request merged**
