### PR TITLE
Fixing auditors

### PR DESCRIPTION
**Pull request by budang**
auditors now work properly/record data correctly

### CODE REVIEW

**Comment by CuriousG102** [comment]
Did you mean to add timestamps to specific scrolled pixels data? Would you like me to? LGTM.

**Comment by budang** [comment]
I can add it. Any other auditors that need a timestamp, maybe _pastes_specific_?

I don't think _keypresses_specific, mouse_movement_specific,_ or _clicks_specific_ would need a timestamp since those actions typically happen very frequently

**Comment by CuriousG102** [comment]
Without timestamp there is no ordering after we put them in the database. So if you think knowing the order or temporal spacing of an auditor's collected data is important then it should have a timestamp.

I also meant to mention: We should really have an auditor that just collects browser type/version. That way when we put it out in the wild we can know if our code is failing on a specific browser.

**Comment by budang** [comment]
Hm. I will probably add timestamps just to _scrolled_pixels_specific, pastes_specific,_  and _clicks_specific_. I feel that typing and moving the mouse occur too frequently for them to have any major significance.

I've been reading up on possible ways to detect a browser's type and version, and it seems the only way is by parsing the User Agent. The problem with User Agents is that many of them list the names of other browsers as well.

For instance, this is my Chromium UA:
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/49.0.2623.108 Chrome/49.0.2623.108 Safari/537.36` 

I found some code off of StackOverflow that seems to do a good job of regex parsing the correct browser name/version, but there is no guarantee it will work for every browser (for example, in the case someone uses an uncommon browser like SeaMonkey, since browser names are hardcoded), or if the UA format changes in the future for some reason.  Although it wouldn't be as informative, a safer thing to do would be to report the entire UA. I'll write an auditor that will parse the name/version out, but just something to keep in mind I guess.

We could also just have a message asking the worker to use Chrome, Firefox, or Safari to complete the task. That way we might not have to worry about checking for uncommon browsers.

**Comment by budang** [comment]
Found a nifty API that might help!

[http://www.useragentstring.com/pages/api.php](http://www.useragentstring.com/pages/api.php)

**Comment by CuriousG102** [comment]
How about we just collect UA and worry about the rest later?

**Comment by budang** [comment]
Fine by me

**Pull request merged**
