### PR TITLE
working multiple_answers (checkbox) step

### PR DESCRIPTION
**Pull request by budang**
also removed the 'randomize order' checkbox for text_input step

### CODE REVIEW

**Comment by CuriousG102** [comment]
Is this the exact same as step multiple choice except for the template and script file? If so we should clean it up. I'll make a pr on your branch with some inheritance.

**Comment by budang** [comment]
Ok, sounds good

**Comment by CuriousG102** [comment]
This fell off my radar. Will take care of it

**Review by CuriousG102 — CHANGES_REQUESTED** [review]
Could you regenerate the migration here after we merge in my most recent PR? My b for not merging this earlier. We can sit down and do this together if desired. Or I can do it. Whatever sounds best.

**Comment by budang** [comment]
I can do it

**Comment by budang** [comment]
Merged your PR, I will take care of this. If it sounds fine with you, I might just do all the (minor) CSS edits on here

**Comment by CuriousG102** [comment]
Minor css sounds fine to me.

**Comment by budang** [comment]
Made the migrations, and for the CSS edits I ended up just adding a bootstrap class

**Review by CuriousG102 — APPROVED** [review]
LGTM. Let's make sure the migrations play nice when both PRs ( #31  and #33 ) are merged.

**Pull request merged**
